// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBg8AozpINsdyEdQza8ywse-XGr0g9wB8I',
    appId: '1:966035109719:web:d2a994c40fc941001a3012',
    messagingSenderId: '966035109719',
    projectId: 'projectx-3ca02',
    authDomain: 'projectx-3ca02.firebaseapp.com',
    storageBucket: 'projectx-3ca02.appspot.com',
    measurementId: 'G-WXTCFENZ3X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJHQGtl-LtRAfQ4bedW_Ocjx7NXFFIslQ',
    appId: '1:966035109719:android:a465df8770f6b8cc1a3012',
    messagingSenderId: '966035109719',
    projectId: 'projectx-3ca02',
    storageBucket: 'projectx-3ca02.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-laiNBabK6_lCduIeRxTXp-oU6o6IxqU',
    appId: '1:966035109719:ios:7a1bf5156711e3731a3012',
    messagingSenderId: '966035109719',
    projectId: 'projectx-3ca02',
    storageBucket: 'projectx-3ca02.appspot.com',
    iosClientId: '966035109719-8f3lekkviormh8dcg40h00q1kku4cat8.apps.googleusercontent.com',
    iosBundleId: 'com.example.cleanArchitectureTemplate',
  );
}
