/// Generated by AssetsRefGenerator - DO NOT MODIFY BY HAND
class Assets {
  static const String assetsIcons = "assets/icons/.gitkeep";
  static const String blueSkyBackground = "assets/images/blue_sky_background.png";
  static const String en = "assets/translations/en.json";
  static const String lightning = "assets/images/lightning.png";
  static const String lightningWithRain = "assets/images/lightning_with_rain.png";
  static const String mapPin = "assets/icons/map_pin.png";
  static const String maxTemperature = "assets/images/max_temperature.png";
  static const String moon = "assets/images/moon.png";
  static const String moonBehindCloud = "assets/images/moon_behind_cloud.png";
  static const String moonBehindCloudWithRain = "assets/images/moon_behind_cloud_with_rain.png";
  static const String oneCloud = "assets/images/one_cloud.png";
  static const String skyBackground = "assets/images/sky_background.png";
  static const String sun = "assets/images/sun.png";
  static const String sunBehindCloud = "assets/images/sun_behind_cloud.png";
  static const String sunBehindClouds = "assets/images/sun_behind_clouds.png";
  static const String sunWithRain = "assets/images/sun_with_rain.png";
  static const String twoClouds = "assets/images/two_clouds.png";
  static const String twoCloudsHeavyRain = "assets/images/two_clouds_heavy_rain.png";
  static const String twoCloudsLightRain = "assets/images/two_clouds_light_rain.png";
  static const String twoSmallClouds = "assets/images/two_small_clouds.png";
  static const String wind = "assets/images/wind.png";
}
